app: # 应用基本配置
  env: local # 环境名称
  port: 9999 # 服务监听端口号
  app_name: gin-app # 应用名称
  app_url: http://localhost # 应用域名

log:
  level: info
  root_dir: ./storage/logs
  filename: app.log
  format:
  show_line: true
  max_backups: 3
  max_size: 500
  max_age: 8
  compress: true

database:
  driver: mysql
  host: localhost
  port: 3306
  database: go_test # 数据库名称
  username: root
  password: 123456 # 密码
  charset: utf8 # 编码格式
  max_idle_conns: 10 # 空闲连接池中连接的最大数量
  max_open_conns: 100 # 打开数据库连接的最大数量
  log_mode: info # 日志级别
  enable_file_log_writer: true # 是否启用日志文件
  log_filename: sql.log # 日志文件名称